### ISSUE TITLE
Map Marker can be way off.

### ISSUE THREAD

**Issue by Maxunit** [Ottermandias/GatherBuddy#1]
Hello Ottermandias,

I am currently using GatherBuddy and noticed, that usually the Map Maker placement is pretty spot on, but I just farmed some Flax and it ported me to Camp Tranquil, but the Flag was placed at the very northern end of the map.

The same just happened (editing as I write) with Underground Spring Water. The first time, it marked the proper spot, now the 2nd time, it placed the marker way off in the South.

**Comment by Ottermandias** [comment]
Hey! This is because I am stupid and can not write X and Y correctly!

**Comment by Ottermandias** [comment]
Fixed here, automatic update in Dalamud pending on pull request.
