### ISSUE TITLE
Spot and Zone filter not working

### ISSUE THREAD

**Issue by Xiniox** [Ottermandias/GatherBuddy#10]
The Spot and Zone filter doesn't register any input for me. Noticed it first after updating to the test version (2.0.2.0). Changing back to 2.0.1.0 didn't solve the issue.

https://user-images.githubusercontent.com/33554580/115111036-99cd5b00-9f7e-11eb-9f7d-18f4969ec3d3.mp4

**Comment by Ottermandias** [comment]
That's just because I can't copy&paste correctly, should be fixed on [T] :D
