### ISSUE TITLE
Fishing window isn't updating info like Location, bait, time cast, etc.

### ISSUE THREAD

**Issue by auxao** [Ottermandias/GatherBuddy#100]
Ty for your hard work!!! [<a href="https://imgur.com/fnT24Sr"><img src="https://i.imgur.com/fnT24Sr.png" title="source: imgur.com" /></a>](url) [New Recording - 6/10/2022, 5:05:17 PM](https://vimeo.com/719273492/67ce9e20c2)

**Comment by Ottermandias** [comment]
As you could read in your video, disable edit mode to get the functionality of the fish timer.

**Comment by auxao** [comment]
Oh my gosh, I'm so embarassed. I thought that was what I did to hide the window the first time, when I installed the plugin. Please forgive my ignorance! I also now understand that simply typing `/gbc edit` des the trick. Again please forgive me, and thank you so, so much for all of your effort. It really is helpful, and greatly appreciated.  
[<a href="https://imgur.com/fnT24Sr"><img src="https://i.imgur.com/fnT24Sr.png" title="source: imgur.com" /></a>](url) N.V.

**Comment by Ottermandias** [comment]
No worries. Have fun with it :D
