### ISSUE TITLE
[Feature Suggestion] A 'Log' column for gatherables

### ISSUE THREAD

**Issue by DenL** [Ottermandias/GatherBuddy#106]
Would be great to have a 'Log' column for gatherables similar to for fishes. I understand it's a one and done thing, but would be so convenient to have for those trying to knock out their gathering log quickly and find out which timed nodes needs to be targeted.

**Comment by KalasB** [comment]
I second this! GB has been super useful for fishing completion, and would definitely help many get their resplendent tools.

**Comment by Ottermandias** [comment]
Just go along your gathering log and use the context menu gather.

**Comment by KalasB** [comment]
I was more referring to the timer functionality for timed nodes as in the fishing tab, but yes it would just be convenience. /gather works too.

**Comment by Ottermandias** [comment]
The problem is mainly that I'd have to first figure out how to get log information about gatherables (wouldn't be hard, but I don't do it yet) and more importantly to keep it up to date (which might very well be a pain). This really doesn't seem worth it for gatherables.
