### ISSUE TITLE
[Feature Request] Ocean Fishing - Spectral Timer

### ISSUE THREAD

**Issue by ryuujin** [Ottermandias/GatherBuddy#115]
Is it possible to add in a way to track the Spectral Current time remaining through GatherBuddy?
Either through a slash command to timestamp the spectral start time so it could be recorded by hitting a macro or starting a stopwatch so you can track the time remaining. Any way to enable manual tracking of the spectral current time remaining or any automatic way would be great.

**Comment by Ottermandias** [comment]
Sorry, but I won't do anything about ocean fishing for the time being.
Imma close this because if I ever touch Ocean Fishing I'll probably don't need this as a reminder :)
