### ISSUE TITLE
Turning off chat log message printing does not work for alarms. Results in [LogKind(JapeneseCharacters)] being printed instead.

### ISSUE THREAD

**Issue by AgentPotango** [Ottermandias/GatherBuddy#123]
![image](https://user-images.githubusercontent.com/73344345/194498213-0ce828b3-05e6-470b-91ba-9d709493382e.png)

Using the above settings, it is expected that no chat messages are printed to the UI for alarms. 

However... Observe the result below: 

![image](https://user-images.githubusercontent.com/73344345/194497804-4ea0764f-63b3-41e5-8d18-4ecc5da2dda9.png)

There seems to be some disconnect here? Maybe I've misunderstood what should be happening but I'm not sure why the message is now prefixed with [LogKind(Japenese Characters)] upon turning off presumably all settings to print to chat. 

Effectively I only want to see the alarms on the side like the following without printing anything into the chat: 

![image](https://user-images.githubusercontent.com/73344345/194498009-afd00422-439b-442e-a3e5-61b2b1030523.png)

Hopefully it's not too difficult to fix!

**Comment by AgentPotango** [comment]
Wow that fast and yes you're correct haha - I alt tabbed to check this and try to delete this issue in the case that this is what I missed. Testing it now, but I'm pretty sure this should solve it.

**Comment by Ottermandias** [comment]
The Chat Type enums are from Dalamud stuff btw, not anything I do myself. I assume that "None" is not "No messages" but "No Chat Type", and that causes the weird symbols. You probably want to keep the chat types on other values.

**Comment by AgentPotango** [comment]
Yep thanks for that - can confirm that no messages show up and yeah you're probably right regarding the weird symbols. Thanks for the help. Apologies for my own error!
