### ISSUE TITLE
[Feature Request] Right-Clicking alarms in the tracker should instantly open the corresponding alarm group so that you can easily and quickly check off items or toggle alarms on/off.

### ISSUE THREAD

**Issue by wirchtalksgames** [Ottermandias/GatherBuddy#137]
As the title says. It's just a bit of annoyance that could be avoided if the context menu when you right click alarms would give an option to open the alarm corresponding to the item you just clicked, so that you don't have to manually open GB and browse to the alarm itself.

**Comment by Ottermandias** [comment]
No.
