### ISSUE TITLE
[Feature Suggestion]

### ISSUE THREAD

**Issue by J4F0** [Ottermandias/GatherBuddy#138]
Don't know if it's allready inthere, but when you put in for example Dark Matter Cluster, it only shows 1 node, while there are several nodes up at the same time.
Suggestion: Show ALL nodes, up and upcoming.

Loving your addon btw :)

J4F0

**Comment by Ottermandias** [comment]
![image](https://user-images.githubusercontent.com/70807659/197333721-2a843640-3844-48e5-ade4-6fda2bf3c421.png)
![image](https://user-images.githubusercontent.com/70807659/197333733-2ef131c2-85d6-4795-b408-1a6852b7533d.png)
