### ISSUE TITLE
Gather Buddy Fail To Launch / Re-Install

### ISSUE THREAD

**Issue by SekhmetLightblade** [Ottermandias/GatherBuddy#14]
I have been using this add on for a while now but suddenly it crashed and now i get this error.,. I have uninstalled it and now it wont reinstall and this is the error that i get. I contacted the discord yesterday and havent heard anything back from them. I don't even know if they are looking at my issue.
![Capture](https://user-images.githubusercontent.com/85028807/120075952-60a20380-c071-11eb-8dcc-f940608e2aa6.PNG)

**Comment by MeetraYarhu** [comment]
This issue happened to me after I attempted to sort by 5.55 fish to display. It showed a similar error, and crashed the plugin. I could not re-open it so I restarted my game, only to find that it was no longer listed in my installed plugins, and I received the same error as OP.

What fixed this was closing my game again, opening the launcher's app settings, and manually deleting it from there.
