### ISSUE TITLE
[Question] Hide the alarm window?

### ISSUE THREAD

**Issue by SgtWiking** [Ottermandias/GatherBuddy#141]
Is it possible to hide the Alarm window while still having the notification/sound popup in the chat?
I cant seem to find it in the settings to just hide it, only disable it. Cheers

![image](https://user-images.githubusercontent.com/16310477/200180087-e403670b-5a4c-4efc-b48c-0116558f6ada.png)

**Comment by Ottermandias** [comment]
There is no Alarm window... That's the Gather Window, which has nothing to do with alarms inherently.

![image](https://user-images.githubusercontent.com/70807659/200180201-cd2363d4-9b13-4d94-99cc-a37af717cf18.png)
![image](https://user-images.githubusercontent.com/70807659/200180208-763d21fa-8f66-4fed-9311-a43457a15c20.png)
you can disable either of those.
