### ISSUE TITLE
Unable to remove items from gbc window

### ISSUE THREAD

**Issue by SirTwill** [Ottermandias/GatherBuddy#149]
I've set up 4 items I want to track, but not only want to track two of them. There doesn't seem to be a way to remove them from the little gbc window without just doing /gbc hide. Which isn't idea as there are two I still want to track.

Apologies if there IS a way to remove them. If there is it isn't very obvious.

**Comment by Ottermandias** [comment]
![image](https://user-images.githubusercontent.com/70807659/208976921-23c8dcd8-421d-4792-b0dc-a5a815b422e6.png)
trash cans

**Comment by SirTwill** [comment]
Found it, thank you very much.
