### ISSUE TITLE
Dravanian Springwater not listed + Mining preference for collectables

### ISSUE THREAD

**Issue by itsdkoda** [Ottermandias/GatherBuddy#150]
I've noticed the Dravanian Springwater does not show up in the program - as well as if you're doing gather quests that both Botanists and miners can get - it will default to miner despite your miner being a lower level. It will also show the mining location - which can be an entirely different location for botanists.

**Comment by Ottermandias** [comment]
![image](https://user-images.githubusercontent.com/70807659/211190172-29932afa-a004-47e7-8103-771164e3b2d0.png)
![image](https://user-images.githubusercontent.com/70807659/211190186-5c0f0faa-5a6d-4ce8-8294-d53a15c6e40b.png)
