### ISSUE TITLE
[Feature Request] Fishing Treasure Maps

### ISSUE THREAD

**Issue by ThalassianFrame** [Ottermandias/GatherBuddy#159]
Currently while /gather works for marking + teleporting to a zone that has a treasure map for both botanist and miner, the maps do not have any assigned locations or aetherytes for fishing, would it be possible to add these in a future update? Spearfishing from Stormblood and forward are a decent alternative to MIN and BTN as far as treasure map gathering goes.

**Comment by Ottermandias** [comment]
I won't. Maybe someone else will. And no, they're not a decent alternative.
