### ISSUE TITLE
Add exception for nodes close to Tertium

### ISSUE THREAD

**Issue by Daggerdoc** [Ottermandias/GatherBuddy#160]
Since the exit from the Tertium aetheryte is so offset from the aetheryte itself I think a check to make sure the node is closest to that exit instead of the aetheryte itself would be helpful. Small optimization but still.

**Comment by Ottermandias** [comment]
You can do this manually in the Locations tab

**Comment by Daggerdoc** [comment]
Oh cool didnt know that. Thank you.
