### ISSUE TITLE
GB watchlist hide/unhide

### ISSUE THREAD

**Issue by necrose99** [Ottermandias/GatherBuddy#163]
![Screenshot 2023-02-26 142834](https://user-images.githubusercontent.com/2396239/221435513-fc95bcb3-e149-4c3d-972c-70553c1dbed6.png)  from gb itself often minimized or exited 

**Your watchlist** ..  the all important  whitescripts/purple scripts list of i need gathering book farming....../etc...
![Screenshot_20230226_023220](https://user-images.githubusercontent.com/2396239/221435959-f22421bf-bbba-485a-8986-a2894ceedd08.png)

adding a tab hear to drag or chuck elsewhere for a time it from view in dungeon mode  or minimize it 
when otherwise not in use a plus 
**YES  PLEASE**  minor QoL improment

**Comment by Ottermandias** [comment]
![image](https://user-images.githubusercontent.com/70807659/221436292-7b113fbb-8b90-4bcb-8231-509168f92bd5.png)
