### ISSUE TITLE
[Unsure what to categorize as] Text alarms with no gathering window

### ISSUE THREAD

**Issue by anthroApologizing** [Ottermandias/GatherBuddy#165]
Not sure if this is a setting I'm messing up or if it's not currently possible (thus would count as a suggestion), but I can't seem to make alarms go off without a gather window visible.  If it's something I messed up in config, I don't know where to set that up because none of my alarms appear in chat unless I have a window up.  If it's not currently possible, it would be nice to have in-chat reminders without needing a window up!  Especially with how cluttered the UI already is in just vanilla.  So in effect, something like the plugin DailyDuty is doing.

**Comment by Ottermandias** [comment]
Alarms have nothing to do with the gather window.
![image](https://user-images.githubusercontent.com/70807659/222402301-23c624d8-c61c-40c2-96b3-6b257eb38582.png)
Disable Show Active Alarms in Gather Window. Or Show Gather Window.
