### ISSUE TITLE
[Feature Request] Show number of available baits

### ISSUE THREAD

**Issue by tmschorr** [Ottermandias/GatherBuddy#166]
Could you do a update, that the plugin can display in the fishing window how many baits you still have in your inventory from the one you just used, because that would be very handy.

**Comment by Ottermandias** [comment]
No I could not, because I already did.
https://github.com/Ottermandias/GatherBuddy/commit/64599f909ea60d21ad50047121b1f6905d783698

**Comment by tmschorr** [comment]
Sorry but i can't fing the function in the config menu.

**Comment by Ottermandias** [comment]
It's not an option. I wrote the code, it will be in the next update.
