### ISSUE TITLE
Regular Hooks aren't displayed in Timer

### ISSUE THREAD

**Issue by ChaosInfinited** [Ottermandias/GatherBuddy#179]
I have the same issue as [Snoobjack](https://github.com/Ottermandias/GatherBuddy/issues/164#issuecomment-1493327914), normal Hooks aren't being shown in the timer, despite being registered in records, tried cleaning up, tried with a fresh .dat file, but to no avail.
![image](https://github.com/Ottermandias/GatherBuddy/assets/96987701/5c58443d-b9a0-4473-b6aa-393bd5c929ab)

Ah, now I've noticed they're registered as `none` hooksets instead of `regular` :thinking:

**Comment by Ottermandias** [comment]
I just checked, it works correctly for me.
Do you have any idea what might be unusual for you? You can also open your log with /xllog and set it to verbose on the top left and see what log messages it prints while catching.
Other hooksets do work?
Do you maybe have a different plugin that might hook OnUseAction and do something with it?
The code is
```cs
    private bool OnUseAction(IntPtr manager, ActionType actionType, uint actionId, GameObjectID targetId, uint a4, uint a5, uint a6, IntPtr a7)
    {
        if (actionType == ActionType.Spell)
            switch (actionId)
            {
                case 296:
                    HookedIn?.Invoke(HookSet.Hook);
                    break;
                case 269:
                    HookedIn?.Invoke(HookSet.DoubleHook);
                    break;
                case 4103:
                    HookedIn?.Invoke(HookSet.Powerful);
                    break;
                case 4179:
                    HookedIn?.Invoke(HookSet.Precise);
                    break;
                case 27523:
                    HookedIn?.Invoke(HookSet.TripleHook);
                    break;
            }

        return _hookHook!.Original(manager, actionType, actionId, targetId, a4, a5, a6, a7);
    }
    ```
    
so it really can't behave differently for Hook than for the other Hooksets...?

**Comment by ChaosInfinited** [comment]
Hi, thanks for quick reply!
Yes, every other hookset, double, triple, precision, powerful seem to work.
Regular hook: 
![image](https://github.com/Ottermandias/GatherBuddy/assets/96987701/ca8c0e85-0a11-4b6d-be80-70fcd78b8df8)
Double Hook:
![image](https://github.com/Ottermandias/GatherBuddy/assets/96987701/ba734f6e-ab03-4c02-843f-519f3c071827)
Regular one lacks any info about the hook method, so seems like OnHooking() isn't being started..?
Can't tell about other plugins, will disable them all and check with GB alone.

**Comment by ChaosInfinited** [comment]
Okay, I found the culprit, I have a plugin that replaces Cast with Hook, while fishing, it stops working when I enable this feature.

**Comment by ChaosInfinited** [comment]
I've tried two that offer the same feature, XIVSlothCombo and XIV Combo Expanded (both 3rd party) - the first replaces icon and action, the latter seems to replace the action in the backend only, as the icon stays the same.

I wonder if assuming Cast action as equal to Hook would cause some harm? I'll try it on my side if that's fine

**Comment by ChaosInfinited** [comment]
Seems to be working nothing.. although I'm not sure if it's safe, as I'm not sure what purpose `none` hookset has..
```diff
@@ -79,6 +79,9 @@ public partial class FishingParser : IDisposable
         if (actionType == ActionType.Spell)
             switch (actionId)
             {
+                case 289:^M
+                    HookedIn?.Invoke(HookSet.Hook);^M
+                    break;^M
                 case 296:
                     HookedIn?.Invoke(HookSet.Hook);
                     break;```

**Comment by Ottermandias** [comment]
Definitely not.

**Comment by ChaosInfinited** [comment]
FYI: I've tested the above for a while, nothing crashed, all I'd get is a `none` fish being recorded in case of a `lost` catch (I got quite a lot of that before, can't tell if it got recorded prior or after using the 3rd party plugins), `won` catches got recorded as they should've been.

If you say it's risky I won't try it any further, as it regards third party plugins I get it's not something you'll look forward of thinking about, but if there's anything I can be helpful with in this issue, pray tell o7

**Comment by Ottermandias** [comment]
I don't know if it's risky, tbh, but treating cast as catch because another (unsupported, cheaty) plugin does things the entirely wrong way is not the reasonable way to deal with this. 
Get them to fix their shit or just simply edit their load priority so they load last (loading later => hooking later => their hook is executed first => GatherBuddy sees what they caused).

**Comment by ChaosInfinited** [comment]
Thanks for advice! I'll just stop using them, was using sloth combo due to casual skills replacements, like hook<->cast or island sanctuary sprint and teleports, at least now I know why they're 3rd. party :)

Have a great day!
