### ISSUE TITLE
gatherbtn for Liminal Station chooses worse (longer) teleport

### ISSUE THREAD

**Issue by icy-** [Ottermandias/GatherBuddy#198]
![image](https://github.com/Ottermandias/GatherBuddy/assets/236808/722a71f1-8a24-42f4-8c95-7321e6677f56)

reproduce with `/gatherbtn mesmer`   which would seek out "Mesmerizing Miniature Materials" , part of newest Custom Deliveries NPC.

Attached is map image of correctly identified  "Liminal Station IV (25.4, 26.2)" .   The command chooses Tertium, the aetheryte northeast of the flag.  While mathematically the distance might be closer, in reality one must fly through the subway hallway north for a distance before doubling back, so you end up not only flying longer, but revisiting your PTSD claustrophobia ^_^.  

So, please have it choose Camp Broken Glass instead for these kinds of flags!

**Comment by Ottermandias** [comment]
You can set that up yourself in the Locations Tab.
