### ISSUE TITLE
Crash to desktop when using /gather [item] command

### ISSUE THREAD

**Issue by AKA-Syenite** [Ottermandias/GatherBuddy#2]
Only reproducible with Elm Logs (including partial match). Haven't encountered the issue with any other item.

Does NOT occur if coordinates option is disabled, teleport and gear swap options have no effect that I've noticed. Crash occurs regardless of what zone character is currently in.

Only tested on one character: https://na.finalfantasyxiv.com/lodestone/character/10049984

**Comment by Ottermandias** [comment]
Huh, doesn't happen to me. On what language are you? Do you have recording on and recorded nodes for Elm Logs?

**Comment by AKA-Syenite** [comment]
Client language is english, recording is on, here's my [GatherBuddy.json](https://pastebin.com/9skSRH0q) from pluginConfigs, not sure how to check whether a specific node is recorded.

**Comment by Ottermandias** [comment]
Hm, when I tested with your json I still got no crash, but the map marker message was malformed (was still working, but "􃂉򁵃Central Shroud ( 20,4  , 20,2 )" wrong text).
But I'm pretty sure this is a Chat Coordinates bug.

**Comment by AKA-Syenite** [comment]
Reinstalled GatherBuddy, and the crash no longer occurs. While I'm not sure what in the records was causing it, it seems to be easily fixed.
