### ISSUE TITLE
[Feature Request] Auto-Mount after Teleport & Job Change

### ISSUE THREAD

**Issue by TheyCallMeZ** [Ottermandias/GatherBuddy#205]
Since most of the time after teleporting you are getting on a mount to fly away to the point of interest. Could a feature be added to auto-mount after changing jobs?

I am unsure of the scope required for either of these options but

Option A: have a dropdown of the character's available mounts to select from.
Option B: Trigger Mount Roulette
Option C: Ask which button to push from the hotbar to get on the desired mount* (I can't be the only one with a mount on my hotbar can I?)

* I don't know how this would function for players who use a controller on PC.

Thank you for your time and consideration, this is a great plugin!

**Comment by Ottermandias** [comment]
No.
