### ISSUE TITLE
[Feature Request] Adjust fish alarm to reflect actual availability

### ISSUE THREAD

**Issue by moosemum** [Ottermandias/GatherBuddy#210]
Specifically, fish that require Fisher's Intuition currently ping their alarm even if there's a catch dependency that isn't fulfilled. The fish log itself reflects this, but the alarms do not.

Example: Aquamaton's available time window is 10:00-16:00, but requires Intuition from 1x Shadeshifter (weather & time dependent) and 5x Shapeshifter (always up), The alarm for Aquamaton's availability will trigger for 10:00 in game, even if Shadeshifter is not available during the 6 hour window.

Example 2: Warden of the Seven Hues does not show up as a triggerable alarm because it is "Always Up". It may technically be "Always Up" but requires Intuition from 3 separate fish that all have various uptimes.

**Comment by Ottermandias** [comment]
Dependency uptimes are not strict requirements, and can not be incorporated into a fishes uptime in a sensible way. No.
