### ISSUE TITLE
Preliminary 6.55 fish info

### ISSUE THREAD

**Issue by Horcrux94** [Ottermandias/GatherBuddy#211]
Some early findings from Fishcord implemented in this commit: https://github.com/Horcrux/GatherBuddy/commit/5f04ff5f702b617478c785a18b5ca4def62fa568

Wrote these by hand so there might be mistakes.

I would open a PR, but github tells me non-collaborators can't open PRs.

**Comment by Ottermandias** [comment]
Oh, I didn't even notice that 6.55 brought fish, otherwise I'd added at least the skeleton data myself already.
Uh, there are no restrictions on PRs on this repo. Most updates of data in the last months were from PRs. Huh.

**Comment by Ottermandias** [comment]
Anyway, merged it.

**Comment by Horcrux94** [comment]
Might be my own work and personal accounts interfering. I know I've made a PR before and got it accepted so i assumed it was a new rule or something.

Anyway, thanks for merging it!
