### ISSUE TITLE
Fish Timer not working while mooching

### ISSUE THREAD

**Issue by Xiniox** [Ottermandias/GatherBuddy#217]
I've tried fishing at different spots, and whenever I mooch, the fish timer doesn't update and is stuck where it was last time I reeled in.

**Comment by FFXIVWytes** [comment]
I'm not sure if it's the same bug but my fish timer has stopped working and is stuck on Unknown (M) regardless of what bait I use, what hole I'm at or what i'm mooching or not mooching.

![GB_bug](https://github.com/Ottermandias/GatherBuddy/assets/80117346/086c84c5-3961-46ca-9b81-d21e8d1de1e6)

**Comment by Ottermandias** [comment]
![image](https://github.com/Ottermandias/GatherBuddy/assets/70807659/58f949df-8abd-42d5-a1ff-b7c7fbf82a5b)

**Comment by Xiniox** [comment]
![image](https://github.com/Ottermandias/GatherBuddy/assets/33554580/25307278-d28d-4378-8888-7f031b85038e)
![image](https://github.com/Ottermandias/GatherBuddy/assets/33554580/0cdb197a-e20e-4c3b-8b36-579d888135a3)

Seems like it should be working for me then, even though it didn't when I fished during these screenshots. Might be a problem with a chat message not appearing in the chat when you mooch?

**Comment by Ottermandias** [comment]
The Cast Your Line is relevant to the Unknowns, Mooching requires a different line, which is not in your log, so probably?

**Comment by Xiniox** [comment]
As far as I know, mooching doesn't write anything in the chat at all. As an example, this is what it looks like when you chain mooch Ku'ers for Ruby Dragon, but the Fish Timer worked fine then.
![image](https://github.com/Ottermandias/GatherBuddy/assets/33554580/ae3d5e99-cca7-4b96-857e-db841baef01e)

**Comment by Xiniox** [comment]
Aah ok, removing filtering for gathering messages completely has fixed it. Guess I'll have to add custom rules for fishing messages until TidyChat gets an option to show the "recast your line" message. Thanks for the help!

**Comment by FFXIVWytes** [comment]
> ![image](https://private-user-images.githubusercontent.com/70807659/301807815-58f949df-8abd-42d5-a1ff-b7c7fbf82a5b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4NzA3NzIsIm5iZiI6MTcwNjg3MDQ3MiwicGF0aCI6Ii83MDgwNzY1OS8zMDE4MDc4MTUtNThmOTQ5ZGYtOGFiZC00MmQ1LWExZmYtYjdjN2ZiZjgyYTViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDEwNDExMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmYTQ3NTBjMjg3ODc4MjliNDY2N2YwNGY2N2VlMTA4NTVkYWYzYTdmMjQ3ZGMwYzgwMDE1MTEwYTljNDliMjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lCqGh_0NdbtxppD5ussYi1uBX0UOLKypQC3dwTAaYjc)

That solved it for me. Thanks for the quick reply!
