### ISSUE TITLE
Suggestion: Alarm for end of fish window as well as beginning

### ISSUE THREAD

**Issue by palateswap** [Ottermandias/GatherBuddy#22]
When you get focused on the fishing you don't always notice when your window for catching it is over. Would it be possible to get either another option for an end alert or just add it to the regular fish alarm? 

Thank you for your time and attention.

**Comment by Ottermandias** [comment]
Doesn't the fishing timer make that pretty obvious?

**Comment by palateswap** [comment]
I suppose, but I tend to get locked on to watching the actual fish and lose track of time, but I suppose that's just a me issue. Still, just a thought, thank you for your response, and all your hard work on this great tool.
