### ISSUE TITLE
Context menu for Gather broken

### ISSUE THREAD

**Issue by SheathedBlade** [Ottermandias/GatherBuddy#230]
I noticed this happening when right-clicking on the location of the node on the right, yet it leads/auto teleports me to the previous node I had used the context menu on for gathering. This only happens when clicking on the location, right-clicking on the item itself, and then choosing the Gather option, will bring you to the correct place.

Right-click on location:
![image](https://github.com/Ottermandias/GatherBuddy/assets/43582942/d643f31f-44b4-4df3-ad0a-ec5aa5dcd55c)

Right-click on item:
![image](https://github.com/Ottermandias/GatherBuddy/assets/43582942/474996f5-2366-4861-8340-ab025d19c365)

**Comment by SheathedBlade** [comment]
Also as a note, the raw dark amber was the item whose location I was clicking on. The titanium gold ore is the incorrect one.

**Comment by Ottermandias** [comment]
The location shouldn't even be right-clickable.

**Comment by SheathedBlade** [comment]
Well, this is more for collectables, since I'm able to right click on those:
![image](https://github.com/Ottermandias/GatherBuddy/assets/43582942/e7fde940-6d37-49ee-891f-400a0c0250e9)

The only context menu item without plugins is the setting of a timer for the next time it pops. And the gather option is right underneath that.

**Comment by Ottermandias** [comment]
Yes, it should not be. I had to figure out a way to find out when the context menu of this window is on an item and when it is on a location. Think I did.
