### ISSUE TITLE
Uncaught fish keep randomly disappearing from the list

### ISSUE THREAD

**Issue by pawsoffuzz** [Ottermandias/GatherBuddy#232]
I have about 30 more Big Fish I am trying to collect, and since the patch, fish will randomly disappear off the "to catch" list.  This has been happening since the launch of Dawntrail. 

The filters I use (and haven't changed are):
-Log:  Show uncaught, Show not in log
-Patch: Show all
-Collectible:  Show all
-Fish type: Show regular fish, Show Big Fish, Show spearfishing

Sometimes the uncaught fish will disappear on their own while I'm fishing at a hole, other times they will disappear as soon as I click on the fish to teleport to its location.

Restarting the plugin doesn't do anything, but uninstalling/reinstalling brings back most fish initially, but then they will start disappearing again.

Warden of the Seven Hues does not show up at all, even with the filters set to show every single fish in-game.

**Comment by Ottermandias** [comment]
Can you show screenshots of your entire window?

**Comment by pawsoffuzz** [comment]
I am so embarrassed.   As I was clicking through tabs and getting screenshots, under "next uptime" I had 'currently available' unchecked somehow.  I've never intentionally unchecked that, so at some point I must have just hit it by accident and never noticed.  

I am SO sorry for wasting your time.     Is there a way to delete this? :(

**Comment by Ottermandias** [comment]
No worries. But I assumed that this would be the issue because I have no clue how this would happen otherwise.
And since Warden of the Seven Hues specifically is Always available (due to just having uptime dependencies on other things) it made sense that it was just toggled off for Available. :D
