### ISSUE TITLE
Missing dawntrail data

### ISSUE THREAD

**Issue by shadowkras** [Ottermandias/GatherBuddy#238]
So, I have an odd issue with my gatherbuddy instalation.
I can right click and see the gathering spot for DT items. But I cannot search for items or create gather groups with them because it doesnt seem like any of DT items are there.

Any clue what could cause this? I didnt want to wipe out the plugin and start over as I have a couple of personalized gather windows I created.

![image](https://github.com/user-attachments/assets/90964a5b-9826-4e60-80d9-5f85512f077b)

**Comment by Ansler** [comment]
I'm having the same issue, thought there might have been a setting or something I was missing but after going through all the menus I can see for the plugin, I can't find any related options.

**Comment by shadowkras** [comment]
Well, version 3.4.2.3 managed to fix it. Thanks!
