### ISSUE TITLE
DT fish not showing

### ISSUE THREAD

**Issue by Pictavienne** [Ottermandias/GatherBuddy#247]
Hey. 

So DT has been out for a lil while now and I still can't see the 7.0 fish in my GatherBuddy. 

 Is there some actions I'm supposed to do on my side for them to show up or is GB just not updated with them yet ?

**Comment by Ottermandias** [comment]
Disable expansion filters.

**Comment by Pictavienne** [comment]
where can i find said expension filters

**Comment by Ottermandias** [comment]
Just go through your fish list and disable any filters in the top list.
