### ISSUE TITLE
Time out of sync

### ISSUE THREAD

**Issue by pincoide** [Ottermandias/GatherBuddy#25]
Since few days ago (at least that I noticed), the time is out of sync. Wheater changes 5 minutes earlier and also ends 5 minutes earlier, also the clock seems 30 minutes late on warnings (game time), not sure what changed server side, but it's all out of sync...

If this thing happens on a regular basis, is probably better to add a setting so that people can adjust the clock manually.

**Comment by Ottermandias** [comment]
![image](https://user-images.githubusercontent.com/70807659/137999625-a0cf8ade-6431-47ea-8aaf-cef344b3a473.png)

**Comment by Ottermandias** [comment]
And yes, your local windows time is used to compute the Eorzea time. And this is correct, since it's based on the Unix Epoch, not any timezone or something like that.
If your plugin-ET is different from the actual ET, your windows time is incorrect.

**Comment by Ottermandias** [comment]
I'd generally recommend keeping auto-syncing time on, if you don't have any strong reason against it. It's just a simple ntp request every once in a while. :)

**Comment by pincoide** [comment]
> I'd generally recommend keeping auto-syncing time on, if you don't have any strong reason against it. It's just a simple ntp request every once in a while. :)

It is, but sometimes doesn't do it for some reason, who knows... :D
