### ISSUE TITLE
[Suggestion] Sort Alarms by Alarm Times &  change color for active alarms

### ISSUE THREAD

**Issue by imgidedin** [Ottermandias/GatherBuddy#29]
![image](https://user-images.githubusercontent.com/19570528/138739100-96ecb173-41e0-41f7-a0c2-f375fa325d86.png)

Example, if ET is 21H, show the alarms inside that time as another color (the text), maybe yellow or green, that way we can find out faster which one to click to teleport.

I had to order this by hand and it was a mess, having it be able to do it, would be great.

**Comment by justn6** [comment]
+1

Alternatively let us create our own gathergroups!

**Comment by cglatot** [comment]
+1

On top of the OP request, allow us to change the order of the alarms -OR- sort the alarms by time.

Though having the colours, similar to the "Timed Nodes" page would be useful. Green = up now, light green = up soon, etc. -OR- alternatively to that, allow us to filter the Timed Nodes page by the Alarms we have set.

**Comment by Ottermandias** [comment]
When I work on it I'll generally improve the alarm interface. No ETA though.
