### ISSUE TITLE
Coords for Dravanian Mistletoe wrong

### ISSUE THREAD

**Issue by Maxunit** [Ottermandias/GatherBuddy#3]
Heyo Ottermandias,

Just reporting another wrongly placed flag for another material I just came across. It is for the timed node for Dravanian Mistletoe.

The Node is at 26.0x-9.0y, but GatherBuddy (I assume) places it at 23.7x-6.2y instead and therefor out of bounds.

Nonetheless, GatherBuddy is such a big help and keep it up! ^^

Cheers,

Maxunit

EDIT: The same kind of applies to Lignum Vitae Log. The Flag is only a bit off, but i thought I just put it in here as well.

**Comment by Ottermandias** [comment]
Hum. I just checked that node. There's a node exactly where the flag is set (after recording), but it doesn't actually spawn, while the one that does spawn doesn't get the flag. I gotta look at this in a bit more detail, but I don't think it's really relevant. It's only off by a bit and when it's up there's a correct marker anyway.
But interesting find, thanks!

**Comment by Ottermandias** [comment]
I have fixed a wrong averaging of nodes that resulted in the first recorded node just being used for coordinates. The flag still won't be exactly on the node, but that's because there are multiple spawn points for some nodes and the records are averaged between them.
