### ISSUE TITLE
Partially broken UI

### ISSUE THREAD

**Issue by PrincessRTFM** [Ottermandias/GatherBuddy#32]
Two parts of the plugin UI are broken:

- [Gathering alarms](https://i.imgur.com/9ZH68vG.png) - the pre-notice and alarm sound boxes have no width so they can't be set.
- [Timed nodes](https://i.imgur.com/9VlzUX9.png) - the miner/botanist and unspoiled/ephemeral checkboxes are mostly cut off.

**Comment by Ottermandias** [comment]
Looks like the CalcTextSize calls while initializing the caches did return 0. Possibly because you were on an icon font in that time or something like that? Is this recurring/reproducible?

**Comment by PrincessRTFM** [comment]
Recurring every single time I open the UI, not just in a single session. I've just never remembered to make a bug report before (sorry) but it's absolutely every time I play the game and open GatherBuddy. I _do_ have a lot of plugins installed, so maybe it's an issue with that, or with a particular plugin?

**Comment by Ottermandias** [comment]
Have you tried reinstalling? I have no idea how to handle this since it does not happen to me and I don't know how to even begin to get it to happen.
If reinstalling doesn't change it it would be great if you could test if it happens with just GatherBuddy installed (renaming your installedPlugins folder and just keeping GatherBuddy in the correctly named folder would probably be easiest)

**Comment by PrincessRTFM** [comment]
A reinstall worked. I guess if it happens again I'll just do the same thing. If it sounds like the cache initialisation returning 0, maybe having the cache getter recalculate if the value is 0 when it's retrieved would help? Alternatively, since this sounds like something neither you nor anyone else has apparently experienced, I can just reinstall when it breaks for me.

**Comment by PrincessRTFM** [comment]
Well, it broke again. No idea why. The only thing that's changed is that I had closed the game and updated one plugin (Glamaholic) between the last time I opened the UI and this time.

**Comment by Ottermandias** [comment]
Probably fixed due to not computing length outside of the imgui draw call in 3.0.
