### ISSUE TITLE
Crash on using /gather command

### ISSUE THREAD

**Issue by thefiz** [Ottermandias/GatherBuddy#33]
When I use the /gather command to teleport to a node, I occasionally get a silent crash to desktop.  Unsure what is causing it, as there is no feedback, but it's happened three times now, so I know it's not a one-off issue.

**Comment by timothybaken** [comment]
I have the same issue. Made macros for all the timed EW nodes and game crashed to desktop when clicking one.
(Was just a /gather X macro, same as I would manually type in chat.)

**Comment by Ottermandias** [comment]
Hopefully fixed due to using macro system in 3.0.
