### ISSUE TITLE
Where are FishTimer coordinates stored?

### ISSUE THREAD

**Issue by IrrepressableEire** [Ottermandias/GatherBuddy#36]
Apologies for the question. I have a laptop/dock setup where the size of the monitor used for FFXIV changes, with an according change in resolution. As such, currently I need to reposition the Fish Timer whenever I swap from laptop to docked mode or vice versa.

I've looked, but neither dalamudConfig.json nor GatherBuddy.json seems to store the screen position of the Fish Timer. I'd like to be able to swap configurations in and out when changing setups like I do with the game client (moving addon.dat) and ACT (RainbowMage). Is this positioning stored in a file or in the registry?

**Comment by Ottermandias** [comment]
In pluginConfigs is not only the GatherBuddy.json but also a folder GatherBuddy, in there are the fish timings.

**Comment by IrrepressableEire** [comment]
Actually it wasn't the fish timings I was looking for, so much as the physical position of the fish timer window. That said, in my efforts to find where you said it was, I did find it somewhere else - in dalamudUI.json.

**Comment by Ottermandias** [comment]
Oh, yeah.

**Comment by IrrepressableEire** [comment]
Thank you all the same!
