### ISSUE TITLE
Fishing window issue

### ISSUE THREAD

**Issue by Minalia** [Ottermandias/GatherBuddy#37]
My fishing window is messed up, crunched into top left of the screen as shown here: https://i.imgur.com/Svbhneo.png

**Comment by Ottermandias** [comment]
You can't fix this with going into the gatherbuddy config, enabling edit mode and moving and scaling it to your desire?

**Comment by Minalia** [comment]
Gather buddy config won't open!

**Comment by Minalia** [comment]
ah yes i got it thanks <3
