### ISSUE TITLE
[Suggestion] Command to gather first item from last reported node alarm

### ISSUE THREAD

**Issue by borkmaster12** [Ottermandias/GatherBuddy#40]
Desired Behavior:
Command would run /gather sequence on the first item in the most recently reported alarm.

Notes:
Please consider altering the default behavior of /gather (no arguments) to perform the function.

Example:

1. Alarm is reported as follows:
[GatherBuddy][Alarm [PS] Elder Nutmeg]: The gathering node for Rarefied Sykon, Rarefied Elder Nutmeg is currently up at Elpis ( 25.0  , 5.7 ).

2. Player runs /gather (no arguments) or /gatheralarm
3. The command behaves functionally the same as if the player had entered: "/gather Rarefied Sykon"

**Comment by Ottermandias** [comment]
![image](https://user-images.githubusercontent.com/70807659/145887366-5ad58a23-1c6c-4cfd-8d92-d0b53d658ed4.png)

**Comment by borkmaster12** [comment]
Thank you! I can't believe I missed that.

**Comment by Ottermandias** [comment]
No worries! It's only in that tooltip I think. :D
