### ISSUE TITLE
[Suggestion] Option to add gather functionality to item context menu

### ISSUE THREAD

**Issue by borkmaster12** [Ottermandias/GatherBuddy#41]
Desired Behavior:
Upon enabling the optional feature in the GatherBuddy configuration menu, a [Gather] option would appear in the right-click context menu for all items. Selecting this Gather option would be interpreted as running the "/gather [item name]" command.

Notes:
This feature would be nigh useless for non-gatherable items. It would be preferable to only add the context menu option to gather if the item selected was a "gatherable", but I wouldn't expect there to be any easy way to make that check. In which case, 
I believe adding the feature as described would be the most reasonable approach.

Example:
Player opens their Custom Deliveries interface, selects Charlemend, and right-click "Art Supplies". In the list, alongside the existing "Search for Item (by Gathering Method)", "Link", and "Copy Item Name" options, there is a "Gather" option. The player selects the "Gather" option. The "/gather Art Supplies" sequence runs based on the player's current /gather settings for GatherBuddy.

**Comment by Ottermandias** [comment]
No, I don't mess with the ingame interface where not necessary.

**Comment by borkmaster12** [comment]
This suggestion is based on a desire to minimize the steps necessary to run the /gather sequence on an item accessible to the player within the in-game interface. I understand your stance on not altering the in-game interface where not necessary.

With that in mind, I have a different suggestion to achieve the same goal - an optional key binding to run the command instead. I've seen this functionality implemented in Price Check, and it seems to work well. What are your thoughts on this approach?

**Comment by borkmaster12** [comment]
I expect you're likely busy, but I want to ensure this doesn't slip through the cracks. I'll open the above point as a separate issue for consideration when you have time.
