### ISSUE TITLE
[Suggestion] Reduce steps to gather items from in-game interface

### ISSUE THREAD

**Issue by borkmaster12** [Ottermandias/GatherBuddy#42]
With few exceptions, when a player wants to trigger the /gather sequence on an item in the FFXIV in-game interface (e.g. inventory, crafting log, custom deliveries, etc.), the most efficient option to do so is as follows:

1. Right-click the item
2. Select 'Copy Item Name' from the context menu
3. Enter "/gather " into the console
4. Paste the item name from their clipboard into the console
5. Execute the constructed command

From a user experience perspective, I believe many would consider this series of steps excessive and increasingly tedious with consecutive iterations. I have seen multiple instances of recommendations for specific solutions to this issue. Examples of which follow:

- Add a Gather option to the in-game interface right-click context menu
- Add a command that runs /gather [current clipboard value]
- Add a key binding that can be used while mousing over an item to execute /gather on the mouseover target

As of the current point in time, none of the above suggestions have been implemented. However, I wanted to open this issue to represent the core problem they are trying to solve, and provide a centralized location for similar suggestions to be made for consideration.

**Comment by Ottermandias** [comment]
Provided in 3.0 when Dalamud updates its context menu facilities.
