### ISSUE TITLE
display map name with the map coordinates while map links are temporarily disabled

### ISSUE THREAD

**Issue by jacob-keller** [Ottermandias/GatherBuddy#44]
It looks like you disabled map linking temporarily for some bug? but it now just displays the X and Y coordinates without displaying the map name at all.

Is it possible to display the map name in addition to the X and Y coordinates, so that it is obvious where the teleport is going? Otherwise there's no way to tell where the teleport will go, and particularly whether its in the same map or not.

I looked at making a PR for this but wasn't sure how to extract the map name from the node.

**Comment by Ottermandias** [comment]
The next version will have regular map flags again, and I won't push an intermediate one before.

**Comment by jacob-keller** [comment]
Oh ok, thanks 👍
