### ISSUE TITLE
Eorzea Time on GB is 20 ish minutes slower than ET in game.

### ISSUE THREAD

**Issue by waxef** [Ottermandias/GatherBuddy#46]
The eorzea time stated in gather buddy is slower than eorzea time in game, causing alarms to be later than actual time.

![image](https://user-images.githubusercontent.com/66883134/147046738-269c0eae-f29c-4e07-8074-6b10285d4e51.png)

**Comment by Ottermandias** [comment]
This is based on your (windows) system time, which is apparently not correct. You need to re-sync your system time, but be aware that this disconnects you from the game.

**Comment by Ottermandias** [comment]
I went through some effort in 3.0 to improve server- and eorzea time detection, but I can not guarantee accurate times without resorting to querying NTP servers, which I don't want to do.
Optimally, people just keep their system time in sync.
