### ISSUE TITLE
Suggestion: Add NodeType "Legendary" and add filters for it

### ISSUE THREAD

**Issue by ackao** [Ottermandias/GatherBuddy#47]
Currently the UI looks like this when I select "Unspoiled":

![image](https://user-images.githubusercontent.com/3639365/147419782-a5c22eed-f990-4d22-a381-203ae0176ba4.png)

But the Legendary nodes aren't actually Unspoiled type. and I'd like to be able to filter them out separately.

**Comment by cimba007** [comment]
Currently it is hard to seperate between nodes for white scripts, purple scripts and legendary as all are contained withoutn "unspoiled".

**Comment by ackao** [comment]
blergh, yeah. i took a look at the existing code and seems like the node type is being pulled from dalamud api? so the only way around this is to hard code it here and i can understand why you wouldn't wanna.

**Comment by cimba007** [comment]
Maybe as a "dirty" workaround .. filter for "rarefied" gives only unspoiled nodes .. why not add an option to filter for nodes that DO NOT contain the search-string? like .. "!rarefied" ?

**Comment by ackao** [comment]
does that work for older content as well? if yes, then that sounds pretty reasonable. 

i'd suggest adding 2 filters: one with, one without. i'm sure some folks would love to see just the scrip gathers.

and on that note, is there any reasonable way to separate out purple/white scrip gathers for filtering? maybe by node level?

**Comment by Ottermandias** [comment]
It's gonna be changed in the next version.
Discerning Legendary based on Folklore-Requirements.

**Comment by Ottermandias** [comment]
Done in 3.0.
