### ISSUE TITLE
Request: Add a class modifier to the /gather command

### ISSUE THREAD

**Issue by johnysandels** [Ottermandias/GatherBuddy#5]
For items that are obtainable with both BTN and MIN, the ability to specify which class you're gathering with in the /gather command, would be really nice.  Items gathered with different classes are usually in completely different areas of the map.

Is a issue with custom deliveries since it always defaults to miner.

**Comment by Ottermandias** [comment]
I don't think it would default to miner, but rather first to the node that has the closest aetheryte to your current position, and then the first node in the zone (which is usually a mining node, I think)
But yeah, I can do that. Also, just level both jobs! :P

**Comment by johnysandels** [comment]
I do level both classes :D  I was just trying to get white scrip equipment for my miner! Thanks!

**Comment by Ottermandias** [comment]
Next release will have /gatherbot and /gathermin that are restricted to the respective job and produce an error if the item is not gatherable with this job. :)
