### ISSUE TITLE
Crashing a ton when using /gatherbuddy UI

### ISSUE THREAD

**Issue by Fermuto** [Ottermandias/GatherBuddy#50]
I'd say around 40% of the time, whenever I click on a node in /gatherbuddy UI to change jobs/teleport the game will crash.

**Comment by thefiz** [comment]
Yep, I thought the disabling of the map flags was because of this, and when they were re-enabled I figured the problem was resolved.. but it's not.  Definitely crashing a lot.

**Comment by Ottermandias** [comment]
Disable them yourselves.

**Comment by Fermuto** [comment]
What? Disabling it nor reenabling it doesn't fix the crashing, I just checked.

**Comment by Ottermandias** [comment]
You crash while having Map Markers disabled in your settings?

**Comment by Fermuto** [comment]
Yeah, crashes with it disabled
