### ISSUE TITLE
Game crashing when click on alarm via UI.

### ISSUE THREAD

**Issue by meanhoe** [Ottermandias/GatherBuddy#54]
Game crashes when right clicking on alarm in UI window after alarm notifies me. Doesnt happen every time but it does happen frequently. With queue times being what it is, makes it very hard to want to keep using this. Such a great addon though. Thank you for your awesome work.

**Comment by AdamRushton50** [comment]
Also experiencing this, hard to replicate unfortunately it just seems to occur randomly

**Comment by Ottermandias** [comment]
Probably the same bug as any gather-crashes. If so, hopefully fixed in 3.0.
