### ISSUE TITLE
[Feature Request] Alarm Folders

### ISSUE THREAD

**Issue by reiichi001** [Ottermandias/GatherBuddy#55]
I'd love to be able to make folders or groups of alarms. Like "white scrips", "purple scrips", "1 star gathered materials", "reducibles", etc.

That way, I could enable a specific group of alarms based on what I what to gather without having to specifically enable/disable like 6-8 at a time.

**Comment by meanhoe** [comment]
This would be an incredible feature. I was actually trying to see if i could actually find the saved alarms so i could at least save that file and make a new one and swap when needed. This would be time consuming but still better.

**Comment by Akareh** [comment]
Leaving a comment here to support the idea. Being able to toggle groups of alarms on/off with ease would be amazing. I like to turn off alarms when raiding/not gathering and this would be a blessing.

**Comment by Ottermandias** [comment]
Done in 3.0
