### ISSUE TITLE
[Bug?] early alarm trigger not working for fish

### ISSUE THREAD

**Issue by WulfRage** [Ottermandias/GatherBuddy#56]
setting an alarm with an early trigger for fish does not work for me anymore. it still triggers at the time of the fish's window and not any earlier. however it works as intended for btn/min nodes. i don't know if it's a problem on my end or a bug.

 i noticed this broke  awhile ago, but it worked just fine pre-EW when i was using it for big fish that require early prep but i caught them all, many thanks to you. so i didn't bother to report this until now as i figured somebody else would have by now but i did a quick look through current issues and didn't spot anything related to this so i figured i'd bring it up as it is pretty important to fishers.

**Comment by Ottermandias** [comment]
Fixed in 3.0
