### ISSUE TITLE
Missing Item: "Jade"

### ISSUE THREAD

**Issue by CodeMagick** [Ottermandias/GatherBuddy#57]
See wiki link for item details. 

https://ffxiv.consolegameswiki.com/wiki/Jade

![image](https://user-images.githubusercontent.com/34559285/149071294-c9708906-240f-4ba4-949d-b0c7f8fb5d6e.png)

**Comment by Ottermandias** [comment]
It's not missing. Match order is described: 
Perfect match (case-sensitive, "Jade" != "jade")
-> First Partial match (case-insensitive contains) (Jade Pea has lower ID than Jade, so comes first)
-> Proximity match.

You can either enter "Jade" or "jad", but "Jade" will lead to peas. This will be changed in the next version though.
