### ISSUE TITLE
[Feature request] Separate bite timers for fish by bait

### ISSUE THREAD

**Issue by retep998** [Ottermandias/GatherBuddy#59]
When fishing, the type of bait you use can have a significant influence on the bite time of the fish. Live bait generally has a much faster bite time than artificial tackle, and mooching is much faster than bait (notably Ku'er). Also in ocean fishing using the right bait for a fish will have a shorter bite time than the wrong bait (there's also a bug in ocean fishing where some fish are marked on the timer window as being unavailable despite me catching them just fine?)

**Comment by Ottermandias** [comment]
Done in 3.0
