### ISSUE TITLE
Issue with Alarm Trigger for Fish

### ISSUE THREAD

**Issue by SilvaLau** [Ottermandias/GatherBuddy#62]
How does the alarm for GatherBuddy work? It says the alarm will trigger in real minutes earlier instead of Eorzean minutes for fish but even though I set it to 5 (minutes), the alarm always only go off when the fish has spawned.
https://media.discordapp.net/attachments/684745859497590843/948061805245243423/unknown.png

**Comment by Ottermandias** [comment]
The offset does not work for fish in 2.x
It's fixed and completely changed in 3.0, which is currently in alpha testing and will soon go to dalamud testing.
