### ISSUE TITLE
[Request] Bring back node type filters in main window or add to alarms/groups from main window

### ISSUE THREAD

**Issue by vrandon21** [Ottermandias/GatherBuddy#65]
Please can we bring back the automatic filters that the previos version had? They were much easier to use in the main window (the ones at the bottom) or at least a way to make something similar, since colums filters are not that good, I can filter the lvl 90 nodes, by putting 90 on the filter, but all the nodes are mixed up, Unspoiled, Regular, Legendary and Ephymeral, because all are lvl 90, and I can't filter them by type because that messes the uptime filter. Also when I tried to copy the already present lvl 90 gatherer group to my gathering alarm, GB just crashed. I didn't find a way to easy add nodes to my groups or alarms, a "add to alarm" or "add to group" button in the Gatherables tab would be a game changer, at least until Dalamud activates the right click fuction I guess that the intent of that, but I'm not sure, until then is a little annoying to add to groups and alarms in a "feeling" endeless drop down window, maybe a filter for the drop down window can help too. 

I wasn't using GB as muchs as yesterday, I only started to use FfXIVLauncher at the start of EW, and I found a lot of great plug ins, yesterday I was finally farming gathering scripts, and without taking credit for this update, because I know it only will get better, the past one was a little more intuitive. Anyway is a great work what you have made, specially in the FSH area. ty.

**Comment by Ottermandias** [comment]
![image](https://user-images.githubusercontent.com/70807659/156896339-dc823785-61e4-455a-b197-f62dc0306197.png)
![image](https://user-images.githubusercontent.com/70807659/156896343-20f46aa1-4c9b-44d0-8a7c-7ab18b904117.png)
![image](https://user-images.githubusercontent.com/70807659/156896349-be39e70c-3026-4053-a776-96a030f46eec.png)
