### ISSUE TITLE
Outdated collectable coordinates

### ISSUE THREAD

**Issue by Kherae** [Ottermandias/GatherBuddy#7]
recently, several collectables were moved, including lover's laurel. addon hasn't been updated to account and still points at the old locations.

**Comment by Ottermandias** [comment]
You can fix this by just going to the right nodes and either pressing the snapshot button in the interface or just generally having recording on. 
You could also record the correct locations and post them here, or just research them and post them, so I can change the location in the plugin itself for the next version, and don't have to do it myself :D

**Comment by Kherae** [comment]
due to my memory, I wouldnt be able to record and post 'em here. I forget too easily. I've tried snapshot, and sometimes it doesnt detect anything despite me standing on the node with it targeted. is there some form of printout for recorded locations?

**Comment by Ottermandias** [comment]
It doesn't add anything because it was already recorded (I hope). I have
the lover's laurel thingies done myself now anyway, but the next
GatherBuddy update is a big one so I'm not yet ready to release.

**Comment by Kherae** [comment]
it wasnt recorded, it took a few tries to get it to record
