### ISSUE TITLE
Occasional Chat Spam

### ISSUE THREAD

**Issue by jmickey** [Ottermandias/GatherBuddy#71]
Hi!

I have an alarm configured that seems to spam my chat (with the wrong location) before triggering the correct alert.

Here is the chat log:

![image](https://user-images.githubusercontent.com/7720995/157087471-33f26ff3-75af-4843-ab74-6d2efd88b93e.png)

Here is the alarm config:

![image](https://user-images.githubusercontent.com/7720995/157087523-e00725c0-8bfb-4dd8-9f54-de8bcdc4b6da.png)

It only happens with Fire Moraine, not with Darksteel Ore, or any other alarms I have configured.

**Comment by Ottermandias** [comment]
This is probably fixed in 3.0.2.0 which was released just now :)

**Comment by jmickey** [comment]
Yep, seems to have fixed it, thanks!
