### ISSUE TITLE
Alarm buggy and often doesn't go off

### ISSUE THREAD

**Issue by PrinceMew** [Ottermandias/GatherBuddy#72]
With the new UI I've tried setting my normal alarms back up for gathering, but either.. only a couple actually go off, or none of them quite suddenly.

**Comment by mpotts8** [comment]
I am having the same issue. No alarms are going off.

**Comment by Ottermandias** [comment]
Can you show me your alarm setup, please?

**Comment by mpotts8** [comment]
> I am having the same issue. No alarms are going off.

So turns out you need to not only enable the main "turn on alarms" button but also the alarm itself and I totally forgot... woops!

**Comment by Ottermandias** [comment]
Yeah, you need to turn on three things at the moment - Alarms in general, the alarm group you're in and the alarm itself. That may be unintuitive, but the idea is more that you can also separately turn everything off. Maybe I should make the default be enabled. :D
