### ISSUE TITLE
Fish timer not showing up and not displaying fishes

### ISSUE THREAD

**Issue by sherlymanggala12** [Ottermandias/GatherBuddy#73]
After I updated the version into v3.0.3.0, the toggle for fish timer doesn't work anymore. I tried to put it on and restart the game, the timer is there but it's not working when I'm fishing and it doesn't goes off if i uncheck the fish timer

**Comment by Ottermandias** [comment]
Yeah, I missed something with the Windowing System Rework. Fixed in the next version, thanks! :)
