### ISSUE TITLE
[Issue] Alarm groups not saving being saved

### ISSUE THREAD

**Issue by RangePup** [Ottermandias/GatherBuddy#74]
I started using the group feature because my FC is building a submersible so we need a bunch of timed node stuff. I set up a whole list of alarms in the Alarms tab, and started taking stuff off as they were no longer needed. After closing and relaunching the game later, the Alarm list still has all the old things in it that I took out.

In an attempt to solve the problem, I tried to just duplicate the list by clicking the "Copy Current Alarm Group" button, and then "Import from Clipboard. I now have two lists. They both exist in the state that I had copied them in. The top one originally had a lot more things in it, and those did not persist upon my most recent relaunch. The bottom one I had removed Rhodonite, which is still there in the list now.
![Gatherbuddy](https://user-images.githubusercontent.com/36058777/158068029-66e479b0-4e7e-42bd-b31f-43195d86d5ca.jpg)

I attempt to redo the process, Copy Current Alarm Group, Import. and it seems to have kept both of the lists in the currently correct state, so I'm thinking maybe it might just be a UI miscommunication that the "Copy Current Alarm Group" is also functioning as a Save or something? I didn't try testing that in depth.

**Comment by Ottermandias** [comment]
![image](https://user-images.githubusercontent.com/70807659/158068873-639171f9-4daf-438c-9215-7612d1d29fc5.png)
Oops.
