### ISSUE TITLE
Issue with items in multiple locations

### ISSUE THREAD

**Issue by Otael** [Ottermandias/GatherBuddy#75]
I primarily use GatherBuddy for items such as Dark Matter Clusters, which spawn in a variety of nodes, often at the same time. After the update, only one unchanging location is showed after searching for the item rather than how it would previously showed every node it could currently be collected at. Would there be a way to re-enable that old feature without me manually adding each individual node to a gather group myself? Or perhaps an option to use the old version of the plugin?

**Comment by Ottermandias** [comment]
Check out /gather next.
