### ISSUE TITLE
[Issue] Item stays in gather window when in an alarm

### ISSUE THREAD

**Issue by DenL** [Ottermandias/GatherBuddy#77]
I am using the default control-right click to remove items in my gather window. I've noticed that if I add an item to alarms (i.e. by creating alarm groups from gather window group), the item stays in gather window after I control-right click remove it, until I manually remove that item from alarm group as well.

Is this the intended behavior?

**Comment by Ottermandias** [comment]
![image](https://user-images.githubusercontent.com/70807659/158839738-8cf5a764-2834-416e-ba15-47ab4cea30df.png)
If you have this on, yes. Turn it off if you don't want it.
