### ISSUE TITLE
Dark Matter Cluster Search

### ISSUE THREAD

**Issue by ArynBlack** [Ottermandias/GatherBuddy#78]
I may be missing something and if that's the case I do apologize for the opened request/issue here. Whenever searching for Dark Matter Cluster, while it does offer a 'best' option, the nature of Dark Matter Clusters having multiple spawn points that are a random chance to spawn makes trying other nodes via the addon suspect if not unwieldy to accomplish.

It used to be that when you searched for it, it would show all active cases of Dark Matter Cluster-possible nodes, is there any chance this could be restored or is there another way to teleport to other available nodes when searching for it?

Thanks in advance!

**Comment by Ottermandias** [comment]
You can use /gather next or create alarms or a gather group with specific locations. There's nothing random about their spawn chances, anyway.

**Comment by ArynBlack** [comment]
Okay, good to know re: /gather next. And I should've clarified, not the node spawn itself but whether or not Dark Matter Clusters actually will show up on the node in question due to being Hidden, which happened not too long ago when I was stockpiling them.

Still, thank you for the info about /gather next!

**Comment by Ottermandias** [comment]
I just posted this gather group in the preset sharing stuff, but I don't test it. See if it helps you or if you find any improvements, it (or a better version) will become a default gathergroup with the next update.

```H4sIAAAAAAAACrWYTYvbMBCG6T8xOodiy5Y/civdUhbapdDeSg9urLJhHTs42kJZ9r/XM97CaNTLwptTcGw/T0YevbLy5snc9Sdv9mbol4dTH4JfzM7c+MthOZ7DcZ7WU+/ncfSHcMn6ccymefCXLNz3ITsv8+/j4DO6NdvuzQ7j42X9vLxdKXd0qdl/fzLvpmkO/QtuPXMb/Ol2MPsiL0u3M18W/8svn+bDyyW2WL/8GvolfD5Oj2H9efnOfJiGf0ftevjtz5l+9sc+3Pul/zl687x7vcjlStTGpvU+lMpapWK2dNka5Spq7SK2dFUdyFVWegiZLV2NRdVVltpFbOnqHMpVJc+L2MJlixbm0s+L2dJVFbAx1M+L2dJVVzBXUhexpattYGPYahexhassYLFRNcrFbOmiTgWNYeIitnQ5XG4kLmJLV4PKDe662EVs4apyWG5Q+kUuZkuXheVGsnYxW7qoU0GuTruILV0NLDeSnGe2dHW43EjGkNjC5ahTQXVpF7OliyoH1aXXFGZLVw3rw7LSLmJLV5dfreeZLVw1vZGA6tK5wWzpqnC5od83mC1dNW4uJ3URW7pw86vQvcFs4Wosbq3UGcVs6cK9zls9hsyWOwdcH1q9VjJbuhyuD5NtCrGlq8X1oc4oZgtXZ6ur7R2YLV01LqP0XGZ2tNdzuH1lutlz2ta6q7XiBpe2AjehnZ5kGzyyOVxtOqo2eGTDLWSl3kRs8GiXjntVLHU0bvD4PwHcBEhqs3oGlLguoUJiG8MjGzD4kxnAcGH7v+rH81/qg7Y5AhMAAA==```

**Comment by ArynBlack** [comment]
Will do! I'll play with and see if I can't make a corresponding series of alarms for it as well.

**Comment by Ottermandias** [comment]
Creating Alarms will just be a matter of clicking "Create Alarms" on this group for the next update (currently it would ignore the location and just create one alarm)
Though that still seems to have a bug, too, where the alarms trigger wrongly.
