### ISSUE TITLE
fishing timer

### ISSUE THREAD

**Issue by AmenneHolelane** [Ottermandias/GatherBuddy#8]
"okay, the fishing flag gets deleted as soon as you start reeling in, so
if (!fishing)
            {
                _start.Reset();
                _bite.Reset();
                _currentFishList = new Fish[0];
                if (!EditMode)
                    return;
            }
just removing the .Reset()s should work for the moment
But I should probably give a user-friendly way to delete a bad record, just in case."

A friend has done all the fishing logs recently and he told me the macro he uses counts up in 5s intervals, max of 50 so could a hard cap at 60s work (and ignore/delete all entries above that)? the delete bad records is good as well just incase

**Comment by AmenneHolelane** [comment]
Feature request: add a hover+keybind for the fishing overlay that would either open the ff14angler site for a fish [here](https://en.ff14angler.com/fish/4900) or [teamcraft](https://ffxivteamcraft.com/db/en/item/4900/)

**Comment by Ottermandias** [comment]
My intention is that a GatherBuddy user would not need to go to teamcraft, cat became hungry or carbuncle plushy to get that information. If the provided information in the new release is not enough for that, you can open another, more fitting issue, I think, so I'll close this for now :)
