### ISSUE TITLE
Unable to teleport from in game log window

### ISSUE THREAD

**Issue by vrandon21** [Ottermandias/GatherBuddy#80]
When an alarm is triggered and the location in the map is pasted in the in game chat window, I'm unable to teleport to said location, I checked in config and all options are marked, but when clicked in the game log window it only opens up the map but doesn't teleport nor changes class, idk if this is a bug or was removed in favor of the gather window, but I found the chat teleport/class change easier than the gather window who's more in game intrusive. I just want to confirm if it's a bug or was removed or if there's some other way to enable it.
![image](https://user-images.githubusercontent.com/71000122/159975341-d8b42658-342d-4388-9c4d-bfcba1e12f07.png)

**Comment by Ottermandias** [comment]
Yes, this is a map link, not a custom "gather this location" magic thing.
If you want to gather the last triggered alarm, use /gather alarm.
> idk if this is a bug or was removed in favor of the gather window
nothing was removed, this was never an option.

When Dalamud someday enables context menus, you'll be able to right-click the item name to gather that, though.

**Comment by vrandon21** [comment]
Really? I remember clicking in the alarm in the un game window and teleporting, weird, guess I was delusional
