### ISSUE TITLE
[Issue] Plugin crashes when deleting items from gather groups

### ISSUE THREAD

**Issue by Jezabel-Boni** [Ottermandias/GatherBuddy#81]
As the title says, the plugin crashes and asks to restart the game whenever I delete an item from a gather group. I can delete items from alarms and gather windows without trouble, it only happens in gather groups. I can reproduce the bug on both my desktop pc and laptop.
Let me know if you need any more information on this.

**Comment by Ottermandias** [comment]
It should only crash when you delete the ~last~ item. Is fixed for quite a while, I just haven't pushed an update yet due to only miniscule fixes.

**Comment by Jezabel-Boni** [comment]
Thank you, that's good to know. I'll just wait for the update then.
