### ISSUE TITLE
Looking for old Glamour Plate Job Names

### ISSUE THREAD

**Issue by AemoSucks** [Ottermandias/GatherBuddy#85]
Needs to be updated to the new full job names rather than the old abbreviations

![image](https://user-images.githubusercontent.com/66163227/163605416-f577f700-36c8-4fc1-a61e-5ce8c29b98db.png)

**Comment by Ottermandias** [comment]
![Uploading image.png…]()

**Comment by Ottermandias** [comment]
Does not need to be updated to anything since this was a feature since before GatherBuddy 1.0
