### ISSUE TITLE
Request: Add a possibility to apply a glam to each gatherer job

### ISSUE THREAD

**Issue by tcomte8** [Ottermandias/GatherBuddy#88]
I'm using a lot the glamours and I was wondering if it was possible to apply a glamour automatically when switching to the good job for the resource targeted.
I think about something like a new space on the configuration window to add the glam ID to apply to the selected job.

**Comment by Ottermandias** [comment]
Already there, Fixed Designs...

**Comment by tcomte8** [comment]
Sorry, I didn't know and find the way to do it.

Could you tell me where the option is please ?

I just see how to switch the gear set but not the glam. I use the same gear for miner, botanist and fisher. But I apply a different glam using a macro. How do you apply the glam desired from the 20 possible with this 6.1 patch ?

**Comment by Ottermandias** [comment]
Wait, sorry, I was in the wrong repo. 
You can link glamours to your gearplates. If you do not do that, GatherBuddy can not do anything for you.

**Comment by tcomte8** [comment]
Oh !! You just has learnt me something ! 

Thanks a lot for taking time to answer and sorry for disturbing.
