### ISSUE TITLE
fishing timer not working if ...

### ISSUE THREAD

**Issue by OthelloRhin** [Ottermandias/GatherBuddy#9]
I noticed after having tested on several fishing spots that the timer did not work if the game was set in a language other than English (French for my part, not testing the others ...).

![ffxiv_FR](https://user-images.githubusercontent.com/9140400/115103946-b0ab8780-9f55-11eb-81a7-7938210bdf43.png) ![ffxiv_EN](https://user-images.githubusercontent.com/9140400/115103937-abe6d380-9f55-11eb-8aec-afe7de58942d.png)

Is this a "normal" problem with the functionality now, or is there a problem elsewhere?

**Comment by Ottermandias** [comment]
It just means my french regexes are wrong. But I generally do not test in other client languages, so that was kinda to be expected.  :/

**Comment by Ottermandias** [comment]
Should hopefully be fixed now on [T], also for German. Please let me know if there's still stuff where it doesn't work. :)
