### ISSUE TITLE
[Feature Request] Set the gear change after the teleport completes

### ISSUE THREAD

**Issue by wingnut1979** [Ottermandias/GatherBuddy#91]
Right now when you click on something to gather a number of things happen.

1) You swap your gear to the appropriate job to gather the item.
2) The map gets marked with a flag of where the item is.
3) You teleport to aethyrite closest to the item.

Now that we have glam plate ability in sanctuaries, coupled with the fact that you can tie glam plates to gear sets..
and that gather jobs mostly share the same gear (but not necessarily the same glam)..

It would be great if the order of those operations was changed so that the gear change (and simultaneous glam change) could occur once you arrived at the aethyrite (sanctuary).

**Comment by Ottermandias** [comment]
Nope. Not GatherBuddys job.
