### ISSUE TITLE
[Suggestion] Config - Gather Window Don't Delete on Empty

### ISSUE THREAD

**Issue by SubaruYashiro** [Ottermandias/GatherBuddy#96]
title.

Currently if item is deleted 1 by 1 until everything is gone the current gatherwindow filter is also deleted.

I have this kind of filter atm, and clearing the list (by modifier to delete item), would cause the next item i add to gather window would be put to 90 star i have.
not deleting the list when all items is deleted on the spot = reusable unnamed / named gatherwindow.
![image](https://user-images.githubusercontent.com/96951106/167295858-c9dc8377-a4d9-41cf-882c-297de2011700.png)

**Comment by Ottermandias** [comment]
Had a small bug in deleting that is now fixed by just not deleting.
